---
# tasks file for roles/docker_kubectl

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt packages
  apt:
    update_cache: yes
    state: latest

- name: Update apt and install docker-ce
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Add remote "ubuntu" user to "docker" group
  user:
    name: "{{ item }}"
    groups: "docker"
    append: yes
  loop: "{{ users }}"

- name: open docker.sock to everyone
  file:
    path: /var/run/docker.sock
    mode: 0760

# install aws cli
- name: Install Python PIP
  apt:
    name: python3-pip
    state: latest

- name: Install AWS CLI via PIP
  pip:
    name: awscli
    state: present

    # install kubectl
- name: Add kubectl apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add kubectl apt repository
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list
    update_cache: yes

- name: Install kubectl
  apt:
    name: kubectl
    state: present
