---
# tasks file for roles/jenkins
- name: Add Jenkins GPG key
  ansible.builtin.get_url:
    url: "{{ url }}"
    validate_certs: no
    dest: /usr/share/keyrings/jenkins-keyring.asc

- name: Add Jenkins repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/"
    state: present

- name: Install Java
  apt:
    name: openjdk-11-jdk
    state: present

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
  notify:
    - Restart Jenkins
    - Display Jenkins initial admin password

- name: daemon-reload
  systemd:
    daemon_reload: true

- name: Start and enable Jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes

- name: Create initialization scripts directory
  file:
    path: /var/lib/jenkins/init.groovy.d
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0775

- name: Add initialization script to setup basic security
  template:
    src: security.groovy.j2
    dest: /var/lib/jenkins/init.groovy.d/security.groovy
  register: security

- name: Restart Jenkins
  systemd:
    name: jenkins
    state: restarted
  when: security.changed

- name: Start and enable Jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes

- name: Download Jenkins CLI jar
  get_url:
    url: http://localhost:8080/jnlpJars/jenkins-cli.jar
    dest: /home/ubuntu
  register: cli_installed

- name: Install Suggested Plugins
  jenkins_plugin:
    name: "{{ item }}"
    state: latest
    url_username: "{{ username }}"
    url_password: "{{ password }}"
    url: "http://localhost:8080"
  loop: "{{ plugin }}"
  when: security.changed
  notify:
    - Restart Jenkins

- name: Download Jenkins CLI jar
  get_url:
    url: http://localhost:8080/jnlpJars/jenkins-cli.jar
    dest: /home/ubuntu
  register: cli_installed

# to change jenkins port
- name: change jenkins port
  lineinfile:
    path: /etc/default/jenkins
    regexp: "^HTTP_PORT=8080"
    line: "HTTP_PORT=8090"
  notify:
    - Restart Jenkins
# - name: Get Jenkins initial admin password
#   slurp:
#     src: /var/lib/jenkins/secrets/initialAdminPassword
#   register: jenkins_password
#   tags:
#     - print1
# - name: Display Jenkins initial admin password
#   debug:
#     msg: "{{ jenkins_password['content'] | b64decode }}"
#   tags:
#     - print1
